table Calendar
	lineageTag: 2a7775c1-8a2f-4e91-aab4-d1bac912169c
	dataCategory: Time

	measure 'Is Top 5 Category' = ```
			
			VAR _CurrentRev = [Total Revenue]
			VAR _Threshold = 
			    MINX(
			        TOPN(5, VALUES(products[Category]), [Total Revenue], DESC), 
			        [Total Revenue]
			    )
			RETURN IF(_CurrentRev >= _Threshold, 1, 0)
			```
		formatString: 0
		lineageTag: 705d897d-34ca-4194-aa0a-0491c78b4edd

	measure 'Month-over-Month new customer growth rate' = ```
			
			VAR _Current = [New Customers]
			VAR _Previous = CALCULATE([New Customers], PREVIOUSMONTH('Calendar'[Date]))
			VAR _Growth = IF(NOT ISBLANK(_Current) && _Previous <> 0, 
			    DIVIDE(_Current - _Previous, _Previous, BLANK()), BLANK())
			RETURN _Growth
			```
		lineageTag: b6df2ca8-adb1-4250-86af-81119ae1db39

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		isUnique
		formatString: General Date
		lineageTag: 73759fc4-1817-49a7-9b45-86297e3da71e
		summarizeBy: none
		isNameInferred
		sourceColumn: [Date]

		annotation SummarizationSetBy = Automatic

	column Year
		formatString: 0
		lineageTag: f6b79582-3ee1-41f0-b133-aa4d1cc47ac7
		summarizeBy: none
		isNameInferred
		sourceColumn: [Year]

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		formatString: 0
		lineageTag: b23f7e17-979b-4066-bf74-afd11446825c
		summarizeBy: none
		isNameInferred
		sourceColumn: [Month Number]

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		lineageTag: 5b5ada0f-ef1e-4b8a-8fae-50489a952a10
		summarizeBy: none
		isNameInferred
		sourceColumn: [Month Name]

		annotation SummarizationSetBy = Automatic

	column 'Month Short'
		lineageTag: 77868901-30eb-43a5-b3ba-69446ce0cf9b
		summarizeBy: none
		isNameInferred
		sourceColumn: [Month Short]

		annotation SummarizationSetBy = Automatic

	column Quarter
		lineageTag: 37735baf-8ba6-4238-bea2-31ed22b42988
		summarizeBy: none
		isNameInferred
		sourceColumn: [Quarter]

		annotation SummarizationSetBy = Automatic

	column 'Quarter Number'
		formatString: 0
		lineageTag: a4ab1f48-305e-4b0e-abbb-2b48bde379d2
		summarizeBy: none
		isNameInferred
		sourceColumn: [Quarter Number]

		annotation SummarizationSetBy = Automatic

	column 'Week Number'
		formatString: 0
		lineageTag: 2f52a528-5708-4158-9b85-62b629e240a7
		summarizeBy: none
		isNameInferred
		sourceColumn: [Week Number]

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		lineageTag: 4f917980-3bfd-40c6-bc86-f6ea9a6d67d5
		summarizeBy: none
		isNameInferred
		sourceColumn: [Day Name]

		annotation SummarizationSetBy = Automatic

	column 'Day Number'
		formatString: 0
		lineageTag: 1c0c8d95-c1de-4701-a1f9-017c5173f568
		summarizeBy: none
		isNameInferred
		sourceColumn: [Day Number]

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		lineageTag: 506a695e-a72e-434a-a4af-45df3cd1996d
		summarizeBy: none
		isNameInferred
		sourceColumn: [Is Weekend]

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		lineageTag: 4b0c063b-fa8b-4806-979b-94ac3856a8eb
		summarizeBy: none
		isNameInferred
		sourceColumn: [Fiscal Year]

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		lineageTag: 75b2119b-9df8-4955-8abd-ee2e410a2788
		summarizeBy: none
		isNameInferred
		sourceColumn: [Fiscal Quarter]

		annotation SummarizationSetBy = Automatic

	column Year-Month
		lineageTag: b746c3e5-2c30-4c5f-bb69-faa7f0fc56b1
		summarizeBy: none
		isNameInferred
		sourceColumn: [Year-Month]

		annotation SummarizationSetBy = Automatic

	partition Calendar = calculated
		mode: import
		source =
				ADDCOLUMNS(
				    CALENDAR(DATE(2016,1,1), DATE(2018,12,31)),
				
				    // ── 1. Year ───────────────────────────────────────────────────────────────────
				    "Year",
				        YEAR([Date]),
				
				    // ── 2. Month Number ───────────────────────────────────────────────────────────
				    "Month Number",
				        MONTH([Date]),
				
				    // ── 3. Month Name (January...December) ───────────────────────────────────────
				    "Month Name",
				        FORMAT([Date], "MMMM"),
				
				    // ── 4. Month Short (Jan...Dec) ────────────────────────────────────────────────
				    "Month Short",
				        FORMAT([Date], "MMM"),
				
				    // ── 5. Quarter Label (Q1..Q4) ─────────────────────────────────────────────────
				    "Quarter",
				        "Q" & CONVERT(INT((MONTH([Date])-1)/3)+1, STRING),
				
				    // ── 6. Quarter Number (1..4) ──────────────────────────────────────────────────
				    "Quarter Number",
				        INT((MONTH([Date])-1)/3)+1,
				
				    // ── 7. Week Number (ISO: Monday=start of week) ────────────────────────────────
				    "Week Number",
				        WEEKNUM([Date], 2),
				
				    // ── 8. Day Name (Monday...Sunday) ────────────────────────────────────────────
				    "Day Name",
				        FORMAT([Date], "DDDD"),
				
				    // ── 9. Day Number (1=Mon, 7=Sun) ──────────────────────────────────────────────
				    "Day Number",
				        WEEKDAY([Date], 2),
				
				    // ── 10. Is Weekend ────────────────────────────────────────────────────────────
				    // WEEKDAY mode 2: Mon=1...Sat=6, Sun=7 → >=6 means weekend
				    "Is Weekend",
				        IF(WEEKDAY([Date], 2) >= 6, "Weekend", "Weekday"),
				
				    // ── 11. Fiscal Year (April start) ────────────────────────────────────────────
				    // Apr 2016 onward = FY2016-17 | Jan-Mar 2016 = FY2015-16
				    "Fiscal Year",
				        IF(
				            MONTH([Date]) >= 4,
				            "FY" & YEAR([Date])     & "-" & RIGHT(CONVERT(YEAR([Date]) + 1, STRING), 2),
				            "FY" & (YEAR([Date])-1) & "-" & RIGHT(CONVERT(YEAR([Date]),     STRING), 2)
				        ),
				
				    // ── 12. Fiscal Quarter (April-start fiscal year) ──────────────────────────────
				    // Apr-Jun = FQ1 | Jul-Sep = FQ2 | Oct-Dec = FQ3 | Jan-Mar = FQ4
				    "Fiscal Quarter",
				        "FQ" & CONVERT(
				            SWITCH(
				                TRUE(),
				                MONTH([Date]) >= 4  && MONTH([Date]) <= 6,  1,
				                MONTH([Date]) >= 7  && MONTH([Date]) <= 9,  2,
				                MONTH([Date]) >= 10 && MONTH([Date]) <= 12, 3,
				                4
				            ),
				        STRING),
				
				    // ── 13. Year-Month (YYYY-MM format for chronological sort) ────────────────────
				    "Year-Month",
				        FORMAT([Date], "YYYY-MM")
				)

