table products
	lineageTag: 6c2b3848-3510-4252-924f-59644efb23d2

	/// Count of distinct product categories that have revenue in the current filter context
	measure 'Active Categories' =
			-- Active Categories
			-- Counts distinct product categories with at least one sale in filter context
			-- Useful as a KPI card on the Product page header
			-- FILTER removes categories with blank/zero revenue (e.g. no orders in period)
			VAR _ActiveCats =
			    COUNTROWS(
			        FILTER(
			            VALUES(products[Category]),
			            NOT ISBLANK([Total Revenue])
			        )
			    )
			RETURN
			    IF(ISBLANK(_ActiveCats), 0, _ActiveCats)
		formatString: #,##0
		displayFolder: 📈 Advanced Metrics
		lineageTag: 87da6773-f189-4c10-a962-1b91036f1ccb

	column product_id
		dataType: string
		lineageTag: 0c2df286-f0cf-4b15-b6f3-5ea5385d8035
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_category_name
		dataType: string
		lineageTag: b140afbb-b639-48db-ab30-6eb8ac65255b
		summarizeBy: none
		sourceColumn: product_category_name

		annotation SummarizationSetBy = Automatic

	column product_weight_g
		dataType: int64
		formatString: 0
		lineageTag: a9251e4f-6426-4946-8002-fabf0075a429
		summarizeBy: none
		sourceColumn: product_weight_g

		annotation SummarizationSetBy = Automatic

	column product_length_cm
		dataType: int64
		formatString: 0
		lineageTag: 4d6e0b9e-7fb0-4d0f-8bb2-bf701bafc470
		summarizeBy: none
		sourceColumn: product_length_cm

		annotation SummarizationSetBy = Automatic

	column product_height_cm
		dataType: int64
		formatString: 0
		lineageTag: a4f5cd29-08e2-42f7-b799-0f51093fb0d6
		summarizeBy: none
		sourceColumn: product_height_cm

		annotation SummarizationSetBy = Automatic

	column product_width_cm
		dataType: int64
		formatString: 0
		lineageTag: d418ae4b-1ac3-4013-8df6-398884e81ac5
		summarizeBy: none
		sourceColumn: product_width_cm

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 33b8ae63-2675-4125-841a-806e5e190842
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition products = m
		mode: import
		source =
				let
				    // Step 1: Load all files from the project source folder
				    Source = Folder.Files("C:\PowerBi\project"),
				
				    // Step 2: Extract the products CSV file
				    ProductsRaw = Source{[#"Folder Path"="C:\PowerBi\project\",Name="olist_products_dataset.csv"]}[Content],
				
				    // Step 3: Parse products CSV (9 columns, Latin-1 encoding)
				    ProductsCSV = Csv.Document(ProductsRaw,[Delimiter=",", Columns=9, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				
				    // Step 4: Promote first row as column headers
				    ProductsHeaders = Table.PromoteHeaders(ProductsCSV, [PromoteAllScalars=true]),
				
				    // Step 5: Cast columns to correct data types
				    ProductsTyped = Table.TransformColumnTypes(ProductsHeaders,{
				        {"product_id",                   type text},
				        {"product_category_name",        type text},
				        {"product_name_lenght",          Int64.Type},
				        {"product_description_lenght",   Int64.Type},
				        {"product_photos_qty",           Int64.Type},
				        {"product_weight_g",             Int64.Type},
				        {"product_length_cm",            Int64.Type},
				        {"product_height_cm",            Int64.Type},
				        {"product_width_cm",             Int64.Type}
				    }),
				
				    // Step 6: Inline translation table (replaces missing CSV file)
				    // Full Olist category name translation list embedded directly
				    TranslationTable = Table.FromRows({
				        {"beleza_saude","health_beauty"},{"informatica_acessorios","computers_accessories"},{"automotivo","auto"},{"cama_mesa_banho","bed_bath_table"},{"moveis_decoracao","furniture_decor"},{"esporte_lazer","sports_leisure"},{"perfumaria","perfumery"},{"utilidades_domesticas","housewares"},{"telefonia","telephony"},{"relogios_presentes","watches_gifts"},{"alimentos_bebidas","food_drink"},{"bebes","baby"},{"papelaria","stationery"},{"tablets_impressao_imagem","tablets_printing_image"},{"brinquedos","toys"},{"telefonia_fixa","fixed_telephony"},{"ferramentas_jardim","garden_tools"},{"fashion_bolsas_e_acessorios","fashion_bags_accessories"},{"eletroportateis","small_appliances"},{"fraldas_higiene","diapers_and_hygiene"},{"fashion_roupa_masculina","fashion_male_clothing"},{"pet_shop","pet_shop"},{"moveis_escritorio","office_furniture"},{"market_place","market_place"},{"eletronicos","electronics"},{"eletrodomesticos","home_appliances"},{"artigos_de_festas","party_supplies"},{"casa_conforto","home_comfort"},{"construcao_ferramentas_ferragens","construction_tools_hardware"},{"construcao_ferramentas_iluminacao","construction_tools_lights"},{"industria_comercio_e_negocios","industry_commerce_and_business"},{"alimentos","food"},{"artes","arts"},{"moveis_colchao_e_estofado","furniture_mattress_and_upholstery"},{"livros_interesse_geral","books_general_interest"},{"construcao_ferramentas_construcao","construction_tools_construction"},{"instrumentos_musicais","musical_instruments"},{"moveis_cozinha_area_de_servico_jantar_e_jardim","kitchen_dining_laundry_garden_furniture"},{"construcao_ferramentas_jardim","garden_tools"},{"fashion_roupa_feminina","fashion_female_clothing"},{"papeis_escritorio","office_supplies"},{"livros_importados","imported_books"},{"sinalizacao_e_seguranca","signaling_and_security"},{"climatizacao","air_conditioning"},{"artigos_de_natal","christmas_supplies"},{"fashion_underwear_e_moda_praia","fashion_underwear_beach"},{"fashion_esporte","fashion_sport"},{"seguros_e_servicos","insurance_and_services"},{"casa_conforto_2","home_comfort_2"},{"livros_tecnicos","technical_books"},{"pc_gamer","pc_gamer"},{"fashion_roupa_infanto_juvenil","toys"},{"portateis_casa_forno_e_cafe","portable_kitchen_food_processors"},{"eletrodomesticos_2","home_appliances_2"},{"la_cuisine","la_cuisine"},{"audio","audio"},{"cds_dvds_musicais","cds_dvds_musicals"},{"dvds_blu_ray","dvds_blu_ray"},{"flores","flowers"},{"artes_e_artesanato","arts_and_craftmanship"},{"musica","music"},{"casa_construcao","housewares"},{"portateis_cozinha_e_preparadores_de_alimentos","portable_kitchen_food_processors"},{"agro_industria_e_comercio","agro_industry_and_commerce"},{"fashion_calcados","fashion_shoes"},{"consoles_games","consoles_games"},{"construcao_ferramentas_seguranca","construction_tools_safety"},{"moveis_sala","furniture_living_room"},{"cinematografia_foto","cinematography_photo"},{"cine_foto","cine_photo"}
				    }, {"product_category_name", "product_category_name_english"}),
				
				    // Step 7: Left-join products with inline translation on product_category_name
				    MergedTable = Table.NestedJoin(
				        ProductsTyped,
				        {"product_category_name"},
				        TranslationTable,
				        {"product_category_name"},
				        "TranslationJoin",
				        JoinKind.LeftOuter
				    ),
				
				    // Step 8: Expand only the English category column
				    ExpandedTranslation = Table.ExpandTableColumn(
				        MergedTable,
				        "TranslationJoin",
				        {"product_category_name_english"},
				        {"product_category_name_english"}
				    ),
				
				    // Step 9: Replace nulls in English category with 'Unknown'
				    ReplacedNulls = Table.ReplaceValue(
				        ExpandedTranslation,
				        null,
				        "Unknown",
				        Replacer.ReplaceValue,
				        {"product_category_name_english"}
				    ),
				
				    // Step 10: Remove unwanted metadata columns
				    RemovedColumns = Table.RemoveColumns(ReplacedNulls,{
				        "product_name_lenght",
				        "product_description_lenght",
				        "product_photos_qty"
				    }),
				
				    // Step 11: Rename English category column to 'Category'
				    RenamedCategory = Table.RenameColumns(RemovedColumns,{
				        {"product_category_name_english", "Category"}
				    }),
				    #"Replaced Value" = Table.ReplaceValue(RenamedCategory,"Unknown","Uncategorised",Replacer.ReplaceText,{"Category"})
				
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

